before_install:
  - "sudo pip install http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz"
  - "git clone https://github.com/jsdoc3/jsdoc"

before_script:
  - "./build.py plovr"
  - "./build.py serve-precommit &"
  - "sleep 3"

script: "./build.py JSDOC=jsdoc/jsdoc precommit"
